### PR TITLE
Business service dereferenced when deleting Stakeholder

### LINKED ISSUE #9: Deletion of a stakeholder generates error on business-service endpoint
Steps to reproduce:
- Create a stakeholder.
- Create a business service with an owner pointing to the stakeholder previously created.
- Delete the stakeholder created in step 1.
- Get the list of business services and we will see an internal server error.

We need to investigate this issue however it seems to be a problem of deleting an entity that has foreign keys associated with it.

### PR DESCRIPTION
**Pull request by mrizzi**
resolve #9 

With soft delete in place, leveraging something like `ON DELETE SET NULL` on the FK for BusinessService entity is not an option because Stakeholder entries are never deleted (i.e. with soft delete, deleting means update `deleted` field to `true`).
So the method
```java
@PreRemove
private void preRemove() {
    businessServices.forEach(businessService -> businessService.owner = null);
}
```
has been introduce to de-reference the Business Service from the to-be-deleted Stakeholder.

For reproducing the issue (and I think we should consider requesting this more in the future) I create a test case in a `issues` folder with the tests folder.

### CODE REVIEW

File: src/main/resources/db/migration/V20210302__alter_business-service.sql [hunk 1]
```diff
@@ -0,0 +1,5 @@
+alter table if exists business_service
+    add constraint UK_btcp3rc4skxn0oyxbbnok68do unique (name),
+    add constraint FK64f0d7vxcp60lyjlttb7dqk3t
+    foreign key (owner_id)
+    references stakeholder;
```
Comment (carlosthe19916) [inline src/main/resources/db/migration/V20210302__alter_business-service.sql:5]: @mrizzi if we add **unique** constraints then we will have problems identifying which **names** can not be used anymore. E.g. I've just made this test in the UI:

- Create a Business service with the name "myBusinessService".
- Delete the previous business service.
- Create a new Business service with the same name as step 1 "myBusinessService", The UI will show an error.

The error itself is correct because the name "myBusinessService" is already in the DB however it was "soft deleted" and the user is not able to see which are the "soft deleted" names so they will try to use them anyways.

Maybe we should think again about the impact in the UI and also in the DB if we decide to continue with the approach of "soft deletion"... As far as I know there are no explicit requirements for having unique names in some entities but for sure it is just a matter of time until it will become a requirement (at least for the UI)

**Review by carlosthe19916 — COMMENTED** [review]
@mrizzi I've tested this PR and it solves the bug described in https://github.com/konveyor/tackle-controls/issues/9 ; however, I added a small comment below, could you please take a look at it and double-check the "unique" constraints introduced in this PR?

File: src/main/resources/db/migration/V20210302__alter_business-service.sql (hunk 1 above)
Comment (mrizzi) [reply src/main/resources/db/migration/V20210302__alter_business-service.sql:5]: good point and it seems like @PhilipCattanach was thinking we should have this requirement about uniqueness for BS's names.
But, tbh, it's also -strictly speaking- out of scope for this PR, so I'll remove it.

**Review by carlosthe19916 — APPROVED** [review]
Thanks @mrizzi. This is PR looks good to me.
