### PR TITLE
Stakeholder update management for referenced entities (Job Function, Stakeholder groups)

### LINKED ISSUE #64: [TACKLE-5] Job function can not be removed from a stakeholder
When updating a stakeholder, if the job function (previously assigned) is set to `null` in the request payload then the DB is not updated accordingly and the stakeholder will be still associated with the job function.

### LINKED ISSUE #66: PUT /controls/stakeholder/{id} does not correctly save "stakeholderGroups" field
How to reproduce:
- Create a stakeholder and assign him at least one group. This can be done using `POST /controls/stakeholder`.
- Edit the previously created stakeholder and change the set of groups assigned before. This can be done using `PUT /controls/stakeholder/{id}`
- The new set of groups assigned to the stakeholder adds the new groups but doesn't delete the previous one.

Here is an example using the UI. In the following video we see a stakeholder with 3 groups and then, using the edit modal, I tried to have only 1 group instead of 3; see that even though the `PUT` call is correct the data is not updated in the backend.

https://user-images.githubusercontent.com/2582866/112292796-c056e980-8c91-11eb-86cb-7a83daf1d718.mp4

### PR DESCRIPTION
**Pull request by mrizzi**
resolve #64 
resolve #66 

The test reproducer:
1. creates new job function (`chef`)
1. uses three already existing stakeholder groups
1. creates new stakeholder referencing entities above
1. creates a new business service with stakeholder as owner
1. removes the owner from the business service
1. (from the issue) removes the job function
1. (from the issue) removes 2 (out of 3) stakeholder groups from stakeholder
1. checks the stakeholder is in the expected state
1. deletes job function, stakeholder and business service to not alter other tests

Fix:
* created a dedicated resource for handling the `PUT` verb for `Stakeholder` resource for *ONLY* updating resources (not creating)
* implemented `equals(Object o)` and `hashCode()` methods for both `Stakeholder` and `StakeholderGroup` to have `remove` and `contains` methods to work properly
* disabled update methods creation from Panache in `StakeholderResource`

### CODE REVIEW

File: src/main/java/io/tackle/controls/resources/StakeholderUpdateResource.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+                return var7.build();
+            } else {
+                throw (Throwable)(new RuntimeException("Could not extract a new entity URL"));
+            }
+        } else {
+            var3.update(var1, var2);
+            return Response.status(204).build();
+        }
+    }
+*/
```
Comment (carlosthe19916) [inline src/main/java/io/tackle/controls/resources/StakeholderUpdateResource.java:84]: Is there a reason to keep this commented code? Can we remove it?

**Review by carlosthe19916 — COMMENTED** [review]
@mrizzi This PR looks good to me, just a minor thing: can we remove the commented code mentioned in my comment below?

File: src/main/java/io/tackle/controls/resources/StakeholderUpdateResource.java (hunk 1 above)
Comment (mrizzi) [reply src/main/java/io/tackle/controls/resources/StakeholderUpdateResource.java:84]: TBH I wanted to put it to have a reference to the auto-generated code the new method is replacing because, in the end, the autogenerated methods were not committed so we have no history of how it worked before.

Comment (carlosthe19916) [reply src/main/java/io/tackle/controls/resources/StakeholderUpdateResource.java:84]: Thanks for clarifying it Marco. Let's keep the comments then

**Comment by carlosthe19916** [comment]
This PR looks good to me after testing it locally and also against the UI. Thanks @mrizzi for fixing these bugs.
